language: node_js
node_js: node
services: 
- mongodb
deploy:
  provider: heroku
  api_key: 
    secure: Au88FVJ7ZDervf63N6PDSNr/NS2T88kI+vpw6K0yYXcR7y5QGdA/e8XP7oBw56LwNyfwB0fVdTZTp+UORNnFxewzrLcntQ1SyUBr5Am6IWwGJ5alwtcCvH2wJtsv8Ym0HqDYLPSJ8H7BhhNJeCvg0uM20w17zoiD1IEpiUgH9XB8EiBYXIPPIRE+z1am6xAv1lNK+/9b1EoimOFqzWlMxdzJhIO/8zPBTJR0Q1p2WSeBGLmAfCSuR2AFS1YTEGGjXJb60z210zkscpdH9zbhai+teGHMwjHsGtyUnRp5ostmK5ygyVP85GDogCAqbRR142N8GA4Wh5IEA9o117WvEra+vcNleI1D0WHSCf1QD34OyanAJH54YWw+St887/xJEJ2CF7BEgKlMTswSUDe2MjOqdwSHXGpTChlJ0m6bWd5yKIohdeLgqrzaA6LySFiHYGoRo4VOdpVH4RX9orbAsNay8FUjZRAiEcGwu8PeQgIHWcCNMSl8taNRGF8Sxrxj17K4G1hBThdjH5ehrgZfpkJ92n851axe3MGXjz3iOqp4Wo0brHyYPhoG/oWsc4pQnfp8X14dgV4pXtuSfedX7lQT0vjZV7mmepa5t+XsddalrrlzWevUHSJf4XvfJQCr/L5J1pKYxlElycDzO5yUNkCmFLhqS09RlWyTSE4beSc=
  app: desolate-cliffs-45967
  on: 
    repo: lnovak2/blog-app-mongoose-challenge-solution